# Generated by Django 4.2 on 2023-04-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_aheadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
